### ISSUE TITLE
Spring Session and User Data

### ISSUE THREAD

**Issue by geoarchitect** [microsoft/ApplicationInsights-Java#1299]
We have a Spring Boot application that we are using to front end our microservices that manages all of our session data. 

It appears that Spring User Sessions should get reported but we arent seeing the data for this.

Do we need to add an event of some sort to track the users and sessions when they are generated? If so what should this telemetry event look like?

Is there an event format we can report that will show User and Session data under the session tabs?

**Comment by MS-jgol** [comment]
@geoarchitect 
What version of the Application Insights Java are you using? 
The Application Insights Java 3.0 version is recommended:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent

Otherwise, not knowing the context, you may want to add JavaScript SDK to track the users, page visits etc. for client-side monitoring: https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript

**Comment by geoarchitect** [comment]
@MS-jgol 

Will 3.0 bind with Spring Session data to set the user and session data for requests and telemetry? Happy to give this a try.

For background, we are working to leverage the Spring Session data on the server side to register this data automatically so we dont need the front end setup across all of our micro services. The only option we have had though is to create a filter that does what is needed based on parameters. 

For anyone else looking for something related to this, this doc was probably the most helpful: 
https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#trackrequest

I think after getting into this and realizing that we would have to define or filter the pages / paths, I think ultimately the only solution is for a team to roll their own events.

**Comment by MS-jgol** [comment]
@geoarchitect 
Have you had a chance to try out Application Insights Java 3.0 version?

To get more insights into the front end  - user sessions and page vies, you should use JavaScript SDK in addition to Java:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript

For custom telemetry, specifically requests, you can use the Java 2.x SDK in addition to the Java 3.0 agent:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-get-started?tabs=maven

Otherwise, for supported custom telemetry check this:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#supported-custom-telemetry

**Comment by trask** [comment]
Closing, please let us know if you are still having this issue
