### ISSUE TITLE
https.nonProxyHosts is not honored

### ISSUE THREAD

**Issue by ab529p** [microsoft/ApplicationInsights-Java#1633]
**Is your feature request related to a problem? Please describe.**

Application Insights Java 3.0 also respects the global -Dhttps.proxyHost and -Dhttps.proxyPort if those are set. However it does not seem to honor -Dhttps.nonProxyHosts.

**Describe the solution you would like**

Since some other apps/destinations requires proxy and some does not, we need applicationinsights to honor -Dhttps.nonProxyHosts to make sure we can reach all endpoints (which some destinations need to use proxy while other destinations cannot go through proxy due to whitelist/etc).

**Comment by trask** [comment]
hi @ab529p!

This one had me stumped, but I found the answer [here](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/doc-files/net-properties.html):

> The HTTPS protocol handler will use the same nonProxyHosts property as the HTTP protocol.

So (unintuitively) you need to use `-Dhttp.nonProxyHosts` instead of `-Dhttps.nonProxyHosts`.

I tested this and it worked for me, let us know if this resolves your issue.

**Comment by ab529p** [comment]
yes this seems to work. thanks!!
