### ISSUE TITLE
How to create a distributed trace?

### ISSUE THREAD

**Issue by konjp** [microsoft/ApplicationInsights-Java#1634]
I have project where I'm using java 11, spring boot, Application insights agent 3.0.3 and two different HTTP clients.

One HTTP client(Netty) is used to fetch data(multiple calls are required to fetch all data using pagination) from service that supports W3C tracing, where _traceparent_ header is required. Application insights agent populates _traceparent_ header with correct value, but every time with complete new _traceparent_ value.

Then after some processing, data is sent to another service using different HTTP client(it is inside jar library), but it is possible to set any header value before request is sent. Application insights agent did not populate traceparent header in this client, but even it was populated probably it would be new trace without connection to first call.

My question is how to correlate these calls into a distributed trace?

Also, there are some log entries(e.g. _log.info()_), that should be also correlated into that distributed trace.

**Comment by trask** [comment]
hi @konjp,

> Application insights agent did not populate traceparent header in this client

What HTTP client library is this that the agent is not instrumenting? (e.g. Apache HttpClient, OkHttp, etc)

> My question is how to correlate these calls into a distributed trace?

what is the overarching operation? e.g. I'm guessing it's not a servlet request, since that should get instrumented already. Is it a scheduled job of some sort? I'm trying to understand if it's something we do (or should) already instrument.

If it's something super custom, then check out this section I just added to our wiki to see if that will address your needs:
https://github.com/microsoft/ApplicationInsights-Java/wiki/OpenTelemetry-API-support-(3.0)#adding-a-top-level-span

**Comment by adamisvk** [comment]
Hi @trask, great feature, thanks! Works like charm for us on 3.0.3 for setting Custom Properties on auto-collected Spans. Had to search the code for APPLICATIONINSIGHTS_PREVIEW_OTEL_API_SUPPORT, maybe you can add to wiki.

**Comment by trask** [comment]
> Hi @trask, great feature, thanks! Works like charm for us on 3.0.3 for setting Custom Properties on auto-collected Spans. Had to search the code for APPLICATIONINSIGHTS_PREVIEW_OTEL_API_SUPPORT, maybe you can add to wiki.

@adamisvk awesome, I just added that to the wiki 👍
