### ISSUE TITLE
Support for Akka (Actors, HTTP)

### ISSUE THREAD

**Issue by apoguy** [microsoft/ApplicationInsights-Java#1901]
**Is your feature request related to a problem? Please describe.**
Right now correlation when using Akka Actors and Akka HTTP is broken as it correlates all actors messages as a single transaction; and for Akka Http it is not correlating calls with other apps.

**Describe alternatives you have considered**
OTEL already has implementations for Akka; this could be added in version 3.2.0.

https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/akka-actor-2.5
https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/akka-http-10.0

**Comment by trask** [comment]
btw here's a snapshot build from CI so you don't have to build it yourself: https://github.com/microsoft/ApplicationInsights-Java/files/7333605/applicationinsights-agent-3.2.1-BETA-SNAPSHOT.jar.zip

**Comment by apoguy** [comment]
@trask, sorry for the delay.

Here's a sample app, it receives a Service Bus message, triggers an Akka Actor message which then sends an HTTP request using Akka Http and replies to another service bus queue: https://github.com/apoguy/AkkaAppInsightsExample

When using app insights, I can just see the request to the external HTTP service (so are the traces):

<img width="686" alt="image" src="https://user-images.githubusercontent.com/5913516/137602746-285b86cc-80be-4cf3-b0b0-afc3841a9de5.png">

Thanks!

**Comment by trask** [comment]
hi @apoguy, I ran the repro locally, the reason you aren't seeing service bus telemetry is because it's using Service Bus SDK 7.0.1, and Application Insights Java only captures telemetry starting from Service Bus SDK 7.1.0 (https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#azure-sdks).

I don't see anything else weird when running the repro though (nothing similar to the endless `FROM_AAS_TOPIC -> akka -> FROM_AAS_TOPIC -> akka ...` shown in the screenshot above).

Can you clarify what I should be seeing when running the repro in case I'm missing something?
