### ISSUE TITLE
Is the project affected by the log4j zero-day?

### ISSUE THREAD

**Issue by florianrusch** [microsoft/ApplicationInsights-Java#2001]
Regarding [CVE-2021-44228 ](https://www.randori.com/blog/cve-2021-44228/), we are trying to identify if the ApplicationInsights Java agent is affected. So far we could not find out if the project uses the specific log4j versions or not.

Can anyone help to find out if the project is affected or not?

**Comment by lplotni** [comment]
Having a look at `./gradlew dependencies` output for all the different sub-projects, looks like the agent is using `logback` and not `log4j`. But having a definite answer from the maintainers would be even more reassuring :)

**Comment by trask** [comment]
hi all!

* Application Insights 3.x Java agent - uses logback
* Application Insights 2.x SDK - uses `System.err` and `FileWriter` (never thought I'd say that was a good thing 😅)

There is one interesting case that deserves special attention:

* Application Insights 2.x SDK `applicationinsights-logging-log4j2` artifact - this is an artifact to ingest logs for users who are already using Log4j2. Users should already be bringing their own version of Log4j2 when using this artifact (and should be upgrading that version or applying the mitigation steps from [CVE-2021-44228](https://msrc-blog.microsoft.com/2021/12/11/microsofts-response-to-cve-2021-44228-apache-log4j2/)). However, the `applicationinsights-logging-log4j2` artifact artifact _did_ have a transitive dependency on Log4j2. We have removed this transitive dependency in the just released 2.6.4, in order to _ensure_ that users are bringing their own version of log4j2 when using it (and that there's no way for this artifact to influence the user's Log4j2 version).

**Comment by lplotni** [comment]
Thanks for the insights 🙏

**Comment by florianrusch** [comment]
@trask Nice! Thank you very much for your comments. I think we can close the issue :-) Thanks again!

**Comment by trask** [comment]
Hi all!

Just want to be clear with our recommendation here for anyone visiting:

If you are using the `applicationinsights-logging-log4j2` artifact, make sure that you are bringing your own version of `log4j-core`.

If you are using the `applicationinsights-logging-log4j2` artifact and unsure whether you are bringing your own version of `log4j-core`, update the `applicationinsights-logging-log4j2` artifact to `2.6.4` and add the latest `log4j-core` dependency to your pom.xml, e.g.

```
<dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-core</artifactId>
    <version>2.16.0</version>
</dependency>
```

**Comment by trask** [comment]
Moved this info/response to dedicated and pinned discussion: https://github.com/microsoft/ApplicationInsights-Java/discussions/2008
