### ISSUE TITLE
Missing Span in client request/response logs

### ISSUE THREAD

**Issue by xsmrcek** [microsoft/ApplicationInsights-Java#2161]
### Expected behavior
I expec Span to be created for our client requests/responces

### Actual behavior
Span is missing when we are logging client request/responces

### To Reproduce &&  Sample Application
Minimal example to reproduce issue can be found [here](https://github.com/xsmrcek/minimal-example)

### System information
Java 15
Kotlin: 1.5.31
spring-boot-starter-parent: 2.5.5
spring-cloud-dependencies: 2020.0.4
zalando logbook: 2.14.0

I am afraid it will be caused by us logging to early, as `Span.current().spanContext.traceId` is returning 0000000000000000000000000000000 when we starting logging. But can you please check anyway? (Span is present when we send request as tarceparent header is populated in request)

**Comment by trask** [comment]
thx for reporting this! it looks like this is fixed in latest OpenTelemetry instrumentation, which is included in the same 3.3.0-BETA snapshot that has the "b3" single header support from #2162:

https://github.com/microsoft/ApplicationInsights-Java/suites/5642301778/artifacts/184377016

**Comment by trask** [comment]
oh, nevermind, I didn't test correctly.

you are mostly correct:

> I am afraid it will be caused by us logging to early

the OpenTelemetry instrumentation stores the context (current span) into the netty attributes, and the webflux instrumentation activates it, which is why when you are inside of the webflux handler you get the valid context (current span), but inside of netty handler you do not

if you want to get the context (current span) attribute from the netty channel attributes, that _might_ be possible

**Comment by trask** [comment]
> if you want to get the context (current span) attribute from the netty channel attributes, that _might_ be possible

fyi in case you want to go down this road: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/5568

**Comment by xsmrcek** [comment]
Thank you! This road doesn't seems suitable for someone with my experiance. But thank you very much for explanation. I will remember it for foture, if I had to do it.
