### ISSUE TITLE
Inconsistent data capture :  Missing (empty) client_City for more than 20% of requests.

### ISSUE THREAD

**Issue by Sachin1O1** [microsoft/ApplicationInsights-Java#2250]
### Expected behavior
client_City data should be in the request table for all the requests captured by application insight.

### Actual behavior
Missing (empty) client_City for more than 20% of requests.

### To Reproduce
requests
| where client_City == ""
| count 

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: 3.2.11
 - OS type and version: Linux
 - Application Server type and version (if applicable):
 - Using spring-boot? We are using spring-boot and other
 - Additional relevant libraries (with version, if applicable):

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

**Comment by trask** [comment]
hi @Sachin1O1, can you enable Application Insights self-diagnostic debugging `APPLICATIONINSIGHTS_SELF_DIAGNOSTICS_LEVEL=debug` and check the `ai.location.ip` that is being reported to the ingestion service in both cases where you are seeing `client_City` and where you are not seeing `client_City`?

this will help narrow down whether the issue is on the Javaagent side or not
