### ISSUE TITLE
could i apply spring-profile?

### ISSUE THREAD

**Issue by cy-jedy** [microsoft/ApplicationInsights-Java#2451]
I checked that azure insight is working. In the way shown in the picture below.
- ![image](https://user-images.githubusercontent.com/104347730/185289384-f746219a-f360-4eca-8903-f18e2fadc5bf.png)

but I'm using spring-profile in my project. I want the settings for Azure-insight to be version-managed. So I changed it to Programmatic configuration.
- ![image](https://user-images.githubusercontent.com/104347730/185289702-5032e845-4c0b-4213-9299-1d2bd3d4c5da.png)
- ![image](https://user-images.githubusercontent.com/104347730/185289737-da33efc7-8f83-432d-8a1d-a13ef04af787.png)

And I changed the configuration.json to suit me. However, it is not loading the file properly. Don't you offer this function?
- ![image](https://user-images.githubusercontent.com/104347730/185290067-ec95633a-9176-4194-8a96-a38613dfca5d.png)
- ![image](https://user-images.githubusercontent.com/104347730/185290434-e55a8122-b53c-4c87-b764-fd97b99b0f7b.png)

Additionally, I have a small question. Looking at the azure insight document, I felt that it recommended 'Addition of a JVM argument' and people followed it. I think libraries are usually provided through maven or gradle. Why does Azure Insight recommend 'Addition of a JVM argument'?(there seems to be little talk of programming configuration in  'ApplicationInsights-java issues tab'.) I am a beginner in programming. So I think it's hard to notice the intention because I don't have enough experience. If there is a reason to recommend the way it works as a jvm argument, could you please let me know?

I'm not English native. So tell me if it's hard for you to understand. thank you

**Comment by jeanbisutti** [comment]
Hi @cy-jedy!

The _applicationinsights.json_ file is loaded by default from the classpath with a programmatic configuration. So, you can put this file in _src/main/resources_.

If you want to use another folder, you can use an environmental variable or a system property, more in the Configuration file path part on [this page](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config).

Spring properties defined in a Spring _.properties_ file are not supported. We are going to update the documentation. Thank you for your question.

Yes, we recommended the addition of a JVM argument because of some limitations of the programmatic way ( JRE and read-only file systems not supported).

**Comment by cy-jedy** [comment]
Thank you. It helped me understand the logging ecosystem.
