### ISSUE TITLE
snakeyaml CVE-2022-25857

### ISSUE THREAD

**Issue by stevendick-swissre** [microsoft/ApplicationInsights-Java#2504]
### Summary

Our container image scanning tool Aqua is reporting [CVE-2022-25857](https://nvd.nist.gov/vuln/detail/CVE-2022-25857) for the snakeyaml library in the App Insights agent JAR.

### Context

While I don't see a lot of risk with this DOS exploit, these security tools are dumb and this is flagged at our highest category of 'critical'. Normally we have to fix these within 7 days, but we've received a 2-month exception to get this fixed as our project has other priorities.

### Expectations

The agent can be upgraded to snakeyaml 1.31, which resolves the CVE.

### screenshot

![image](https://user-images.githubusercontent.com/83642283/188906159-01d22d74-f8a7-4ed6-be8d-504107ae68f2.png)

**Comment by jeanbisutti** [comment]
Hi @stevendick-swissre,

Which version of Application Insights are you using?

**Comment by jeanbisutti** [comment]
@stevendick-swissre _snakeyaml_ is a transitive dependency: _otel-java_ ->  _otel-java-instrumentation_ -> _Application insights_. [The dependency was upgraded last week in _otel-java_ project.](https://github.com/open-telemetry/opentelemetry-java/blob/66285e2cbeb618a1f087eafe2a1a453305ae301f/dependencyManagement/build.gradle.kts#L26). An _otel-java_ release will happen this week, and a few days later there will be an _otel-java-instrumentation_ release. So the issue should be fixed in next _Application insights_ release (in less than two months).

**Comment by trask** [comment]
snakeyaml version has been updated to 1.31 in ApplicationInsights Java 3.4.0 release that just went out

(we are also tracking another snakeyaml CVE which doesn't affect Application Insights but should make it into an Application Insights in about a month or so https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6642, please open another issue if this one is also being flagged by your scanner so that we can keep you posted on it)
