### ISSUE TITLE
Custom Operation Id not working using  Sdk 2.x and agent 3.1.1 and 3.3.1

### ISSUE THREAD

**Issue by odiego-developer** [microsoft/ApplicationInsights-Java#2510]
Hello all! 

I'm trying to set a custom operation and parent id in my trace telemetry using the following code:

```
          TraceTelemetry traceTelemetry = new TraceTelemetry(); 
           traceTelemetry.getContext().getOperation().setId(<my_id>);
           traceTelemetry.getContext().getOperation().setParentId(<my_id>);

```
However, the ids are not being reflected in the app insights trace logs.

The problem is not happening in the 2.6.1 agent version: 

![image](https://user-images.githubusercontent.com/71214085/189392016-37684ea9-f73a-44f1-9ebb-6d4665d354d2.png)

**Comment by trask** [comment]
hi @odiego-developer! can you describe the significance of the id? do you use it to correlate the logs with a request or background job, or some other system? thx

**Comment by odiego-developer** [comment]
Hi, @trask ! Yes, sure! 

It's background job: we're using the logs to measure the layers in the context of this background job and I'd like to correlate those layers and dependencies to this background task.


However, I just realized that I can use open telemetry api to do this correlation:

`       Tracer tracer = GlobalOpenTelemetry.getTracer("background-tasks"); 
        Span span = tracer .spanBuilder("background-task-executor-"+taskUuid).startSpan();
        span.setAttribute("backgroundTaskUuid", taskUuid);

        try (Scope ignored = span.makeCurrent()) {
            //layers and dependencies to be correlated here.
        }  finally {
            span.end(Instant.now());
        }`

It's working fine now, but not sure if it's the bast solution.

Thank you!

**Comment by trask** [comment]
@odiego-developer that's great to hear! I'd recommend setting span kind to `SERVER` or `CONSUMER` so that the span will map to the `requests` table instead of an `InProc` dependency.

Also, a slightly easier option than dealing with Tracer and makeCurrent(), is to use the `@WithSpan` annotation, I just updated our docs to mention this: https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#add-spans

But there's also nothing wrong with the approach you've taken.
