### ISSUE TITLE
Custom properties aren't present in Request telemetry. 

### ISSUE THREAD

**Issue by xsmrcek** [microsoft/ApplicationInsights-Java#2533]
### Expected behavior
Custom properties are present in Request telemetry. (it works with applicationinsights-core 2.6.4).

### Actual behavior
Custom properties aren't present in Request telemetry. 
It's kinda follow up for https://github.com/microsoft/ApplicationInsights-Java/issues/2327, as it worked just fine with applicationinsights-core 2.6.4. SO I closed issue. I found that it's not working again, after migrating to new agent.

### To Reproduce
Please use sample application

#### Sample Application
Please use RabbitTest (it needs docker to run) from this example together with agent from resources (just adjust connection string in applicationinsights.json)
https://github.com/xsmrcek/minimal-example

### System information
* SDK Version:
   * applicationinsights-agent-3.4.0
   * opentelemetry-api 1.16
   * applicationinsights-web 3.4.0
 * OS type and version: it behaves the same on windows/linux under Java 15 (compiled by 15 or 17)
 * Using spring-boot
    * spring-boot-starter-parent 2.7.0
    * spring cloud 2021.0.3
  * Kotlin
      * kotlin 1.6.21
      * kotlin-coroutines 1.6.2
 * Additional relevant libraries :
     * io.projectreactor.rabbitmq reactor-rabbitmq 1.5.4

**Comment by trask** [comment]
hi @xsmrcek! since you are using kotlin, please note the javadoc on the OpenTelemetry `makeCurrent()` method:

> Kotlin coroutine users SHOULD NOT use this method as the [ThreadLocal](https://docs.oracle.com/javase/8/docs/api/java/lang/ThreadLocal.html) will not be properly synced across coroutine suspension and resumption. Instead, use withContext(value.asContextElement()) provided by the opentelemetry-extension-kotlin library.

can you update that and see if you still have issues?

**Comment by xsmrcek** [comment]
HI @trask , thank you for pointing it ou!
I fixed it in my code (at least I hope I did it right).
But my problem here is with RequestTelemetry not spans (but this fixed something else :D ).
I have problem with this:
```
telemetryRequest.properties.put("CustomKey", "my attribute")
```
Custom properties aren;t present in application insights on request.
![image](https://user-images.githubusercontent.com/50624143/195627015-5647dbc4-a0c8-40c2-b625-73ecd66d7db1.png)
It works on Spans but not this custom request.

**Comment by xsmrcek** [comment]
Hi @trask , do we have any update here? It's kinda critical bug for me

**Comment by trask** [comment]
hey @xsmrcek can you update your repro with the kotlin changes, and I will re-test?

**Comment by xsmrcek** [comment]
Hi @trask , I updated it. Thank you!

**Comment by trask** [comment]
hey @xsmrcek, sorry for the slow feedback, I _think_ I see the issue now.

[here](https://github.com/xsmrcek/minimal-example/blob/master/src/main/kotlin/org/example/minimalexample/messaging/RabbitListener.kt#L78) you are starting a span but not ending it

[here](https://github.com/xsmrcek/minimal-example/blob/master/src/main/kotlin/org/example/minimalexample/messaging/RabbitListener.kt#L89) you get the current span that you started above, but as an Application Insights Classic SDK `RequestTelemetry` instance

[here](https://github.com/xsmrcek/minimal-example/blob/master/src/main/kotlin/org/example/minimalexample/messaging/RabbitListener.kt#L110) you call `trackRequest` on that `RequestTelemetry` instance.

For starters, I would remove the `trackRequest()`, and add `span.end()`.

I also had to change the TraceFlags [here](https://github.com/xsmrcek/minimal-example/blob/master/src/main/kotlin/org/example/minimalexample/messaging/RabbitListener.kt#L135), because the test was setting TraceFlags.getDefault() which caused the span not to be recorded/exported.

Also, if you `setSpanKind(SpanKind.SERVER)` on the span you create, it will show up in the Application Insights requests table.

In general, I'd recommend using the OpenTelemetry API where possible and try not to mix in `TelemetryClient` unless necessary. It's not clear to me that you need `TelemetryClient` or associated `ThreadContext` in your example.

**Comment by xsmrcek** [comment]
Hi @trask ,
thank you very much for complex response. I fixed my code and it works now :)
Thank you very much!
