### ISSUE TITLE
Update jackson/jackson-databind to 2.13.4

### ISSUE THREAD

**Issue by woglinde** [microsoft/ApplicationInsights-Java#2613]
### Expected behavior
No CVEs findings by security scanners like trivy

### Actual behavior
When running trivy against the 3.4.2 release the following CVEs are reported

- CVE-2022-42003
- CVE-2022-42004

because the version of jackson-databind is still 2.13.3

### Solution
Update to jackson/jackson-databind 2.13.4
(sidenote: opentelemetry 1.19.0 also updated to this version)

**Comment by krishnaklgr** [comment]
please update it to 2.14.0-rc2 as 2.13.x has vulnerabilities reported.

**Comment by trask** [comment]
Application Insights is not vulnerable to these CVEs since it only uses jackson-databind when sending to (and receiving back from) Azure Monitor backend services.

We are updating the jackson-databind dependency in #2618, and also switching to managing the jackson dependencies directly (instead of getting them transitively via the azure sdk library), so that dependabot will update the dependency right away when there are new releases.

The next monthly release is scheduled for approx. mid-Nov.

**Comment by trask** [comment]
hi @krishnaklgr! is the commons-text vulnerability the same as #2597, or something new?

**Comment by krishnaklgr** [comment]
> hi @krishnaklgr! is the commons-text vulnerability the same as #2597, or something new?

Yes @trask , its the same was the fix released with 4.3.2?

**Comment by trask** [comment]
yes, commons-text was updated in 4.3.2

**Comment by trask** [comment]
> @trask , these vulnerabilities blocking our application image build process as they are showing up from agent jar

we discussed today and moved up our next release, which is now targeted for the end of next week

**Comment by trask** [comment]
Version 3.4.3 has been released with this update: https://github.com/microsoft/ApplicationInsights-Java/releases
