### ISSUE TITLE
Logback events are missing OperationIds with new agent version

### ISSUE THREAD

**Issue by krishnaklgr** [microsoft/ApplicationInsights-Java#2615]
### Expected behavior
java logback events are marking with no operationId and Ids.

### Actual behavior
logback logging events that are pushed to AppInsights are not holding traceid and spanIds (OperationId and Ids). It was working with previous agent jar.

**Comment by trask** [comment]
hi @krishnaklgr!

Starting from 3.4.0, "standalone" logs (which are not part of any request) no longer report an id or operation id, since they are not part of any distributed trace (which is what the id and operation id are used for).

Previously "standalone" logs would each generate their own "operation id" ("trace id").

As we are aligning more and more with OpenTelemetry, and standalone logs don't have any "span context" (distributed trace), there is not really an operation id / parent id anymore for standalone logs.
