### ISSUE TITLE
Response codes > 300 are treated as failed

### ISSUE THREAD

**Issue by rdpeake** [Microsoft/ApplicationInsights-Java#281]
Our server returns lots of "304 not modified", however this library only flags responses between 200 and 300 as success.

Is there an intention behind this choice?

**Comment by adriaanthomas** [comment]
Same problem here.

Looking at [the code](https://github.com/Microsoft/ApplicationInsights-Java/blob/master/web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebRequestTrackingTelemetryModule.java#L120) it suggests this is intentional, but it looks strange to me. Why not do a `telemetry.setSuccess(response.getStatus() < 400)`?

**Comment by OriYosefiMSFT** [comment]
will consider response codes >=400 (with the exception of 401) as failures. Anything under is considered success,
