### ISSUE TITLE
NotSerializableException when using TelemetryClient with Apache Storm

### ISSUE THREAD

**Issue by sasincj** [Microsoft/ApplicationInsights-Java#301]
Hi, 
I'm using Application Insights to capture Custom events and Exceptions occurring in my Storm Topology. I have used TelemetryClient Class in my Bolts as follows:
`private TelemetryClient telemetry = new TelemetryClient();`

When I run my topology, I'm getting NotSerializableException  on TelemetryClient  class. PFB Exception StackTrace:
```
Caused by: java.io.NotSerializableException: com.microsoft.applicationinsights.TelemetryClient
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183) ~[?:1.7.0_80]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547) ~[?:1.7.0_80]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508) ~[?:1.7.0_80]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431) ~[?:1.7.0_80]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177) ~[?:1.7.0_80]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347) ~[?:1.7.0_80]
```

Does it make sense to implement this class using Serializable interface or Should we write a custom serializer for this Class?

**Comment by gupele** [comment]
Hi,
Thanks for your input.

I'm not sure that the TelemetryClient should be serializable. You can overcome by making it static or write a custom one

**Comment by OriYosefiMSFT** [comment]
@sasincj, can you please elaborate a little why the TelemetryClient needs to be serializable in Storm? 
I'm not a Storm expert and I am not sure I understand the need. 

Thanks

**Comment by jgogstad** [comment]
Serializing `TelemetryClient` makes as much sense as serializing `HttpClient` or `RestTemplate` - it doesn't. You don't want to serialize object graphs that you don't control, I'm sure if you start digging in the dependency graphs for any of the classes above, you'll discover that they are quite large, and requiring the whole object graph - in essence the entire library - to be serializable isn't viable.

If you're going to serialize and send an object, and that object has a reference to something that isn't data, then you have two options:

1.  Mark the fields as `transient` and implement `readObject(java.io.ObjectInputStream in)`. Initialize whatever state you need, like `TelemetryClient` in `readObject`.
2. Restructure your code so that DTOs only contains data.

Read more about `readObject` in the documentation: https://docs.oracle.com/javase/8/docs/api/java/io/Serializable.html

**Comment by sasincj** [comment]
Thank you all for your suggestions. As a workaround I have created a new Class which extends `TelemetryClient` and Implemented that with `Serializable `interface and I was able to get rid of `NotSerializableException`. 
So My class looks like this,

`public class TelemetryWrapper extends TelemetryClient implements Serializable {}`
