### ISSUE TITLE
Event Hub SDK instrumentation not emitting 'EventHubs.Process' after upgrade from 4.3.9-> 4.3.10

### ISSUE THREAD

**Issue by andrejpk** [microsoft/ApplicationInsights-Java#3084]
### Expected behavior
When using Azure EH SDK version 

### Actual behavior
Describe what actually happened that was unexpected.

### To Reproduce

Using the following dependencies: 
```xml
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-messaging-eventhubs</artifactId>
			<version>5.15.3</version>
		</dependency>
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-messaging-eventhubs-checkpointstore-blob</artifactId>
			<version>1.16.3</version>
		</dependency>

		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>applicationinsights-runtime-attach</artifactId>
			<version>3.4.10</version>
		</dependency>
```

with this EH client setup:
```java
		var clientBuilder = new EventProcessorClientBuilder()
			.consumerGroup(eventHubConfig.getConsumerGroup())
			.checkpointStore(checkpointStore)
			.processEvent(this::processEvent)
			.processError(errorProcessor)
			.processPartitionInitialization(this::processPartitionInitialization)
			.processPartitionClose(this::processPartitionClose)
			.trackLastEnqueuedEventProperties(true);
```

when we were using 4.3.9, we saw requests of `name=EventHubs.Process` but after upgrading to 4.3.10, we no longer get any of these. Other app code and config is the same. 

### System information
Please provide the following information:
 - SDK Version: 4.3.10
 - OS type and version: Docker/Linux
 - Application Server type and version (if applicable):
 - Using spring-boot? Yes
 - Additional relevant libraries (with version, if applicable):

### Screenshots
Our instrumentation showing the EventHub dependencies compared to our manually emitted dependencies by AI SDK version:
![image](https://github.com/microsoft/ApplicationInsights-Java/assets/1774478/a2a97479-652b-4cb7-b972-cb78789b9090)

**Comment by heyams** [comment]
@andrejpk can you submit a sample app for me to repro at https://github.com/microsoft/ApplicationInsights-Java-Repros?

**Comment by andrejpk** [comment]
Hi @heyams I can try to do that next week.

**Comment by mskuba01** [comment]
here is a [fork](https://github.com/mskuba01/ApplicationInsights-Java)

with list of changes I did trying reproduce success scenario on tag 3.4.9:
build related changes:
1) I simply removed grpc related smoke tests, cos I can't build it on Mac OS due to absent native support of protobuf compiler from your build. However using brew I'm able to install it. So didn't dive in that details, just removed.
2) renamed in root rootProject.name = "ApplicationInsights-Java". On Mac it's case sensitive. so can't be just lowercased
3) modified SystemInformationTest. Cos I have Mac OS and it's just one reason of test fail. Would be a sense to change to version I'm proposing.
reproducing related changes:
4) TestUtils - we don't have hardcoded connection string, so make sense to extract it to env variables, so users could plug their settings.
5) EventHubsExporterIntegrationTest.setupTest() I didn't understand why you replacing it w/o doing setups. I had NPE every time I tried to run it with AZURE_TEST_MODE=LIVE. Seems like you trying to skip some scenarios. It's ok, but for other - setup still needed. So I added super.setupTest(testInfo);
6) modified regularTelemetryPlayback.json to use our endpoint, but seems like it was no effect. Somewhere https://test.in.applicationinsights.azure.com/v2.1/track should also be replaced but I didn't find where exactly. All other places seemed to me as unrelated to EventHubsExporterIntegrationTest.

Test run.

I tried to run EventHubsExporterIntegrationTest.producerTest() and had next problems:
1) debug level: Failed to load any of the given libraries: [netty_tcnative_osx_aarch_64, netty_tcnative_aarch_64, netty_tcnative.
As I'm on Mac OS M1, tried to built successfully tcnative for my platform, but somehow it had no effect. [I did all steps here](https://netty.io/wiki/forked-tomcat-native.html). Maybe something else remained, but I was not clear what exactly.
Maybe I need to load it in memory, but anyway this problem seems like not important.

2) 10:52:56.748 [reactor-http-nio-2] ERROR com.azure.core.implementation.jackson.ObjectMapperShim - Package versions: jackson-core=2.14.2, jackson-databind=2.14.2, jackson-dataformat-xml=unknown, jackson-datatype-jsr310=2.14.2, azure-core=1.35.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot
java.lang.LinkageError: Package versions: jackson-core=2.14.2, jackson-databind=2.14.2, jackson-dataformat-xml=unknown, jackson-datatype-jsr310=2.14.2, azure-core=1.35.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot

didn't dive here
3) despite updating references to AI to another I saw
*************************
Application Insights Java failed to connect to https://test.in.applicationinsights.azure.com/v2.1/track

Not sure from where it appears.

I saw 3 events coming to asyncString.subscribe(  value -> { });
First time - something like encoded or encrypted so can't say what is exactly there. Two other times - just empty value. But I didn't see 'EventHubs.process' for the version 3.4.9 I expected to see. So can't move forward from current point.
Maybe something happening in first encrypted message.

**Comment by heyams** [comment]
@mskuba01 that fork is forking applicationinsights-java. can you provide a link to repro this issue? 
can you repro using https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.4.9?

**Comment by mskuba01** [comment]
I can't run [EventHubsExporterIntegrationTest.java](https://github.com/microsoft/ApplicationInsights-Java/blob/main/agent/azure-monitor-exporter/src/test/java/com/azure/monitor/opentelemetry/exporter/EventHubsExporterIntegrationTest.java) due to issues I mentioned.
As Andrej mentioned - we have a hope that once you enable test you might see the problem on your CI.
In fork you can see changes I applied to the project to make it more pluggable to other envs.
As of now project has a lot dependencies on your CI.

**Comment by andrejpk** [comment]
To expand on @mskuba01's comment -- since this is an EventHub.consume scenario (not easily reproducible in the Sprint REST scenario in the repro repo linked earlier), we thought it better to repro using this repo (application-insights-Java)'s own integration tests instead of writing a new repro. That's what @mskuba01 is trying to do.

**Comment by heyams** [comment]
@mskuba01 i will check out your fork. now i understand it better. thanks.

**Comment by mskuba01** [comment]
we found additional details related to this issue. On older versions, starting from 3.4.0 and till now we see behavior when EH.process in case of usage blob checkpoint replacing to blob events, like AzureBlobStorageBlob.setMetadata and AzureBlobStorageCont.listBlobFlatSegment. If we are using in-memory checkpoint, this replacing is not happening. Last version where we don't see this - 3.3.1.
Also if on versions 3.4.0+ publisher will add property {"Diagnostic-Id": ""}, then this replacement to blob doesn't happen.
Java publisher adds it by default. VC code plugin or python client - do not

**Comment by andrejpk** [comment]
@heyams -- @mskuba01 create and shared a private repro repo: https://github.com/mskuba01/reproduce_ai_eh (can't share this publicly due to some IP issues w a small chunk of the code)

**Comment by andrejpk** [comment]
Here's a break-down of the scenarios:

![image](https://github.com/microsoft/ApplicationInsights-Java/assets/1774478/462e005f-d3ff-4bdc-bbfa-7e1860b8ce97)

**Comment by heyams** [comment]
thanks, repro will be useful. i will check and then get back to you.

**Comment by heyams** [comment]
per Liudmila's comment, 

> EventHubs.process behavior is similar to https://github.com/Azure/azure-sdk-for-java/issues/32807 - would you mind adding dependency on newer azure-core to check? (1.39.0 or 1.40.0)

**Comment by mskuba01** [comment]
in repo shared above azure-core 1.40 in use. It doesn't help in our case.

**Comment by andrejpk** [comment]
@heyams it seems that this is still a bug, even using the fixed version of the EH SDK that Liudmila mentioned in 32807. 
In recent testing w the newest EH SDK, in Java agent 3.4.9 we get EventHubs.process and with >= 3.4.10 we don't get that request at all.

**Comment by pdefreitas** [comment]
I've reproduced the problem of on eventhubs `5.15.6` on AppInsights `3.4.12` on the repro provided in #3147. This bug seems to fix my problem but I guess ideally we could be able to do sampling overrides on EventHub spans 👍

**Comment by heyams** [comment]
@andrejpk/@mskuba01 which version of java agent did you use to see 'EventHubs.Process" were emitting? 
i have used your sample app using 3.4.0, i didn't find it in the log. 

Additionally, your app is using 
```
<dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-messaging-eventhubs-checkpointstore-blob</artifactId>
      <version>1.16.6</version>
    </dependency>
```

and didn't use the following though
```
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-messaging-eventhubs</artifactId>
  <version>5.15.3</version>
</dependency>
  ```

**Comment by mskuba01** [comment]
as stated [here](https://github.com/microsoft/ApplicationInsights-Java/issues/3084#issuecomment-1584603507)
Last workable version of AI is 3.3.1 emitting 'EventHubs.Process" in AI logs w/o diagnostic-id usage.

I just built in my my repro project dependency tree `mvn dependency:tree` and do see

[INFO] +- com.azure:azure-messaging-eventhubs-checkpointstore-blob:jar:1.16.6:compile
[INFO] |  +- com.azure:azure-messaging-eventhubs:jar:**5.15.5:compile**

Not sure why are you referencing to <version>5.15.3</version>.
I played with different versions of azure-messaging-eventhubs and other azure libraries and didn't see any differences regarding mentioned bug.

Versions I used were latest on the time we opened bug, except AI lib.
AI lib version my repro project is using - 3.4.0 as it was the first not properly workable version. Raising it in a sequence we mentioned to latest you will see symptoms we stated.

**Comment by heyams** [comment]
@mskuba01/@andrejpk there is an [upstream fix](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/8916) for this. we will make the fix available in our next release around July 19, 2023. this is a heads up.

**Comment by grzesrap** [comment]
I have a lot of EventHubs.process request errors with code 0 also with SDK version 3.4.17
![image](https://github.com/microsoft/ApplicationInsights-Java/assets/47226621/f0fec75e-7631-4f32-8a7d-6032ad7aa9d4)

**Comment by trask** [comment]
hi @grzesrap! can you open a new issue for this, and include whether there is an exception record attached to this request record?
