### ISSUE TITLE
WebApp name is not found, unable to register WebApp

### ISSUE THREAD

**Issue by pankajmahajan10** [microsoft/ApplicationInsights-Java#370]
Hi,

I am having an error running the application insights log4j appender when running my application. It works fine if I load the WAR file in a tomcat server. The error I get is:

AI: ERROR 19-04-2017 17:33, 318: Exception while fetching WebApp name: 'org.apache.felix.framework.BundleWiringImpl$BundleClassLoaderJava5 cannot be cast to java.net.URLClassLoader'
AI: ERROR 19-04-2017 17:33, 318: WebApp name is not found, unable to register WebApp

Quick response will be very helpful.
Thanks in advance.

**Comment by Dmitry-Matveev** [comment]
The current implementation of the Java SDK does not support custom class loaders that do not inherit from (or rather could not be cast to ) URLClassLoader as per [this code](https://github.com/Microsoft/ApplicationInsights-Java/blob/master/web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java#L264).

Thus, BundleClassLoadedJava from felix.framework.BundleWiringImpl is failing the cast and cannot be used to identify the URL to fetch the name for the registration. Loading WAR in tomcat server should work fine because it will use standard class loader.

**Comment by pankajmahajan10** [comment]
is there a solution or work around for this yet? We are currently integrating AppInsights within a custom JIRA plugin and facing the error.

**Comment by littleaj** [comment]
If you are still having this issue with the latest version, please reopen.
