### ISSUE TITLE
When instrumentation key is set null or incorrect, it should report error or exception

### ISSUE THREAD

**Issue by lizzha** [Microsoft/ApplicationInsights-Java#419]
When instrumentation key is set null or incorrect, calling telemetryClient to track telemetry doesn't report error or exception.

**Comment by dhaval24** [comment]
@lizzha I think that there is no check for checking wehther the IKey being set is correct or not, and I believe this is a non fatal error (you don't see telemetry on portal if IKey is wrong). The reason I think it is not checked is that, it will add an added test of pinging one of our endpoints and will generate needless latency in the SDK and the client application. Please let me know if your application is breaking because of this clause.

**Comment by dhaval24** [comment]
@lizzha Let me know if I answered your question in my previous comment so that we can close this issue. 
Thanks

**Comment by dhaval24** [comment]
@lizzha as mentioned above this feature is as design and therefore I am closing this issue. Please feel free to reopen if you have more information on what is breaking.
