### ISSUE TITLE
Catching Throwable/Error

### ISSUE THREAD

**Issue by littleaj** [Microsoft/ApplicationInsights-Java#435]
I’ve noticed that there are a lot of catch blocks which just catch Throwable and do not rethrow anything. The Java documentation discourages catching and “eating” [Errors](https://docs.oracle.com/javase/6/docs/api/java/lang/Error.html) in general, but this is especially true when  [ThreadDeath](https://docs.oracle.com/javase/6/docs/api/java/lang/ThreadDeath.html) is caught. From the docs: “If `ThreadDeath` is caught by a method, it is important that it be rethrown so that the thread actually dies.”

I'm proposing the following policy moving forward: errors should be allowed to propagate upwards unless there is reason we can recover from the error, e.g. LinkageError.

**Comment by Dmitry-Matveev** [comment]
For quite some time AI SDKs were following the guidance to avoid crashing the application due to an issue within SDK. I think this still holds true, so for all internally generated exceptions we would still need to catch all except for `ThreadDeath`, probably. SDK functionality is affected in this case but no effect is propagated into the application itself which is of most importance in the production systems.

Locally, in debug mode, we might throw to ensure all parameters are passed in correctly and the feature is used as intended and all exceptional situations are handled.

Following both of this approaches we may allow for non-disruptive production operation and all issues addressed during the development.

**Comment by dhaval24** [comment]
@littleaj at one point you were working on the PR to correct the issue you found in the SDK. Is the branch / PR out there and were you able to follow @Dmitry-Matveev suggestions?
