### ISSUE TITLE
Sanitize NULL values in strings

### ISSUE THREAD

**Issue by debugthings** [Microsoft/ApplicationInsights-Java#443]
Certain systems can return null values in the exception message. This can cause problems when sending the telemetry and cause it not to be captured by Application Insights.

**Comment by dhaval24** [comment]
@debugthings can you specify if this particular thing is being caused by null messages in the exceptions. As far as I see in the code if the exception has no message then we populate the Message field of ExceptionDetails with the name of the Exception class itself .(https://github.com/Microsoft/ApplicationInsights-Java/blob/bc4a4a486c889c4bdc7c16ec7c977aa190ede546/core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java#L195)

There is further more sanitization when we write this Exception message to the JSON as this is a required field, just in case there was null or empty value we populate it in with the default value (https://github.com/Microsoft/ApplicationInsights-Java/blob/bc4a4a486c889c4bdc7c16ec7c977aa190ede546/core/src/main/java/com/microsoft/applicationinsights/telemetry/JsonTelemetryDataSerializer.java#L208)

As you had communicated with the customer and identified this issue can you provide with the steps to repro this issue so that we can further investigate?

**Comment by debugthings** [comment]
Ah yes, to be a bit more clear the message itself wasn't null. But instead, it had null characters embedded in the string itself. An example message would look something like:

CRM1000001`NUL`ABCDEF`NUL`20170101--Record.

The byte stream for this would decode to these escape characters.

CRM1000001`\0`ABCDEF`\0`20170101--Record.

**Comment by dhaval24** [comment]
@debugthings thanks for specifying this. I am suspecting this something which is a part of stacktrace which also gets packaged with the exception? And do you know anyway to reproduce this exact issue?

**Comment by debugthings** [comment]
I think you can create a new exception with a null character, ie. but i have not tested this outside of the markdown editor.

```
Exception newex = new Exception("This\0is\0broken.");
```

**Comment by dhaval24** [comment]
@debugthings got it now. I believe they are the nulls coming in between the String and possibly we are not escaping it. I will verify add a condition in our sanitization logic if its missing.

**Comment by dhaval24** [comment]
@debugthings I tried this : telemetryClient.trackException(new NullPointerException("This\0is\0broken"));
and the exception still comes on the portal. 

![image](https://user-images.githubusercontent.com/16353121/31351248-38459f0e-acdf-11e7-8d5b-cea549f15066.png)

I double checked that there is sanitization for escape characters like this in the latest version. So I am still not getting the repro. Apologies here but would need more details.

**Comment by debugthings** [comment]
@dhaval24 Interesting, I've asked for the actual log file with the full byte stream of the message to see if it's something else. One other trait of the message (aside from the nulls) is it had a series of \x00 in the string. But I'll send over the actual data once I get it.

CRM1000001`NUL`ABCDEF`NUL`20170101--Record.\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00

**Comment by dhaval24** [comment]
@debugthings yes the \x0000 is an expected thing. This was ported from Dot Net into java to sanitize characters which are not escape sequences. There might be other escape characters which might be missing from sanitization logic. I will submit a PR towards that.
