### ISSUE TITLE
FixedSampling is not reliable since itemCount is set with SamplingScore rather than SamplingPercentage.

### ISSUE THREAD

**Issue by anandsugumaran** [Microsoft/ApplicationInsights-Java#535]
When FixedRateSampling is enabled and sampling percentage is set while tracking the events, sampleRate in the JSON is set with SampleScore rather than the sampling percentage.

Ex, If the sampling percentage is set as 100 then the itemCount is supposed to be 1. Since sampling percentage(100) is overwritten with the samplescore (hash of the operationid = 11.104063601747184) , itemCount is showing the value of 100/sample score (100/11=9) which might not makes sense.

The issue is present in the below class and line no is 116.

Class: com.microsoft.applicationinsights.internal.channel.sampling.FixedRateTelemetrySampler

**Comment by dhaval24** [comment]
@anandsugumaran I am not sure how you could do that with v1 i.e set Dependency A to be filtered with 50% and dependency B to be sampled by 100%. Looking at the code I cannot see that, but may be I missed something. However, I think you can do this pretty easily in v2 by creating a custom Telemetry processor and in the process method check if the Telemetry is of type RemoteDependencyTelemetry, if yes then cast the Telemetry to RemoteDependencyTelemetry and then check the data object to peek out the name which must match the name of specific dependency you want with different sampling rate. Once this check is passed you can then set the sampling percentage there. 

You can then glue this custom processor in the pipeline and sampling v2 will respect the sampling percentage you set explicitly.

**Comment by anandsugumaran** [comment]
@dhaval24 I see that in v2 , Sampling will work only when the samplingPercentage is set to null as per the below lines of code.

```
if (samplingSupportingTelemetry.getSamplingPercentage() == null) {

                    samplingSupportingTelemetry.setSamplingPercentage(samplingPercentage);

                    if (SamplingScoreGeneratorV2.getSamplingScore(telemetry) >= samplingPercentage) {

                        InternalLogger.INSTANCE.info("Item %s sampled out", telemetry.getClass());
                        return false;
                    }
                } else {
                    InternalLogger.INSTANCE.info("Item has sampling percentage already set to :"
                            + samplingSupportingTelemetry.getSamplingPercentage());
                }
```

So If I set the sampling percentage in my telemetry, then the telemetry will not sampled at all.

So this is how i did in v1. I could see that InProcessTelemetryChannel expects telemetrySampler to be not null to enable the sampling in its send method.

```
if ((telemetrySampler != null) && (!telemetrySampler.isSampledIn(telemetry))) {
 return; }
```

To make the telemetrySampler not null , I added the below lines in the config file. I derived at these lines by going through the ApplicationInsightsXmlConfiguration class.

```
<Sampling>
                <Fixed>
                        <SamplingPercentage>10</SamplingPercentage>
                </Fixed>
</Sampling>
```

So once sampling is enabled , then i create the remote dependency like below and track it with TelemetryClient class.

```
RemoteDependencyTelemetry dependencyTelemetry = new RemoteDependencyTelemetry();
            dependencyTelemetry.setName("A");
            dependencyTelemetry.setCommandName("sample");
            dependencyTelemetry.setDuration(new Duration(100));
            dependencyTelemetry.setSuccess(true);
            dependencyTelemetry.setType("A");
            dependencyTelemetry.setSamplingPercentage(50); // i can decide the percentage for each dependency type.
          telemetryClient.trackDependency(dependencyTelemetry);   
```

This worked like a charm except the fact that itemCount is showing values based on Sample score rather than SamplePercentage. I am not sure of the reason why SampleScore is set in place of SamplePercentage here

`samplingSupportingTelemetry.setSamplingPercentage(Double.valueOf(telemetrySamplingScore));`

Also apart from all this , I could see that sampling happens by comparing the hash of the operationId. So its not guaranteed that sampling will work accurate and item count value can no way be reliable.

Eg, Out of 10 req if all the 10 req's  hash value of the operation id is greater than 50 and our sampling percentage is 50% , then none of the operation will be logged. So we cannot rely upon the itemCount for stats at any point of time since operation id is generated in random fashion.

**Comment by dhaval24** [comment]
@anandsugumaran if I recall correctly, the allowed sampling percentage to see the itemCount in the correct fashion is by to have sampling percentage in the form of 100/N.  The backened which does the processing of itemCount is slightly different and designed this way.

so valid sampling percentage would be = 50, 33, 25, 20, 10...

Now what you are referring to in v2 which inhibits you to solve this problem for setting separate sampling percentage programatically is precisely this check:

if (samplingSupportingTelemetry.getSamplingPercentage() == null)

Correct me if I am wrong here. Further, why operation id based sampling makes sense? Because it helps to keep the correlated telemetry together. Otherwise you won't be able to get the E2E trace of the call and monitoring would be of no use :-) Does this answer your question to some extent. 

Regarding why it has been done in the way you mentioned in v1, I am not sure. I can check though.

**Comment by anandsugumaran** [comment]
@dhaval24 Yeah we are setting the sampling percentage as you mentioned. Mostly its 50 , 10 or 20.

Yeah the null check will be failed so my telemetries are not sampled out. Ideally the code snippet

```
if (samplingSupportingTelemetry.getSamplingPercentage() == null) {

                    samplingSupportingTelemetry.setSamplingPercentage(samplingPercentage);

                    if (SamplingScoreGeneratorV2.getSamplingScore(telemetry) >= samplingPercentage) {

                        InternalLogger.INSTANCE.info("Item %s sampled out", telemetry.getClass());
                        return false;
                    }
                } else {
                    InternalLogger.INSTANCE.info("Item has sampling percentage already set to :"
                            + samplingSupportingTelemetry.getSamplingPercentage());
                }
```

should be changed to 

```
if (samplingSupportingTelemetry.getSamplingPercentage() == null) {

                    samplingSupportingTelemetry.setSamplingPercentage(samplingPercentage);
                   
                } else {
                    InternalLogger.INSTANCE.info("Item has sampling percentage already set to :"
                            + samplingSupportingTelemetry.getSamplingPercentage());
                }

 if (SamplingScoreGeneratorV2.getSamplingScore(telemetry) >= samplingPercentage) {

                        InternalLogger.INSTANCE.info("Item %s sampled out", telemetry.getClass());
                        return false;
                    }
```
to make the v2 of the sampling work. 

I am not saying that operation id is a bad choice. My point is, with the current algorithm (SamplingScore) , we cannot guarantee that sampling will work accurate. Eg If you set the sampling percentage as 50 and if you create 10 dependency telemetry then ideally 5 of your calls should be sampled out. But with the current design , it can not be guaranteed. There is chance that all 10 calls could be sampled out since all 10 may generate a sampling score greater than 50.

Yeah if you could check the v1 way, that should be good as well.

**Comment by dhaval24** [comment]
@anandsugumaran got your point. This would be more of feature discussion internally. v1 sampling was based on user-id based sampling. It had it's issues in cross component correlation, and also possible security concerns. 

Further, statistically yes if you make only 10 dependency calls and then set sampling to 50% yes there won't be any gurantee because of randomness. But now you take around 100000 dependency calls in the system all being drawn from IID then setting the sampling to 50% would sample out around 48k - 52k request, anywhere in between these, which is within approximate delta.

I would say if your application is not producing enough traffic, then I would advise not to use sampling at all. I understand that your COGS can go up, however the kind of data you will pump to AI would be very skewed in this case and hence could cause issues in pinpointing the root cause diagnostics. (Though this is just a suggestion, you are free to use sampling as per the need) but as per the points you made with such a small traffic it won't be reliable.  More reliable could be adaptive sampling which dynamically adjusts the sampling percentage based on rps. However, currently it is not available and the v1 version is not stable (it can cause more problems then solving :-) )

**Comment by anandsugumaran** [comment]
@dhaval24 I just gave the numbers for explanation. Since we are currently having around 13 Million dependency calls per day , we would ideally want to sample the dependencies. Yeah that delta is what makes the sampling process in accurate but that's fine for the moment.

Can you please update the thread once sampling is fixed. We are spending way too much than our budget in AI due to this and we would like to have this ASAP. Since we don't have the user id for our telemetry , v1 always picks the operation id for hashing. So that was not a problem for us.

**Comment by dhaval24** [comment]
@anandsugumaran, I see 13 million is a really big number. Wow! Yes I will fix the null statement to appropriate work-around you mentioned.  We will try to have this included in the stable release expected in Mid-February. However, for the time being you can have the changes locally and build the code if needed. I can provide you with the steps if you are willing and have that urgency.

Further, if you find sometime we are very willing to accept any external contributions. If you could submit a PR for this change depending on the time you have, it would be much appreciated.

**Comment by anandsugumaran** [comment]
@dhaval24 Sure , I will try to see if I find time for this and update this thread.
