### ISSUE TITLE
Redirect quick start doc

### ISSUE THREAD

**Issue by grlima** [Microsoft/ApplicationInsights-Java#598]
This doc: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-quick-start  is outdated and not the main starter place for Java monitoring with AppInsights. We should redirect it to this one: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-get-started. This is the main doc which we keep up-to-date as much as possible.

**Comment by mrbullwinkle** [comment]
@grlima in this instance you won't be able to redirect the quickstart to the other doc, but we can definitely link to the more in depth getting started doc you reference at the top of the quickstart doc, and can update the underlying content in the quickstart so it isn't out of date.

Anything that lives under the quickstart, tutorial, overview, and landing page TOC sections follows a specific tightly controlled design pattern that was implemented to create uniform experiences across all the services under Azure docs. Things in the lower half of the TOC where the get started, how-to, and concepts content lives we have much more flexibility.

**Comment by nikmd23** [comment]
Since our [app-insights-java-get-started](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-get-started) doesn't fit the mold required for a Quickstart, I propose we close this issue, and open another one to update [app-insights-java-quick-start](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-quick-start).

**Comment by dhaval24** [comment]
Closing in favor of #730
