### ISSUE TITLE
Numerous CWE weaknesses after upgrading to 2.0.1

### ISSUE THREAD

**Issue by tobiasb** [Microsoft/ApplicationInsights-Java#644]
After upgrading a project to version 2.0.1 I get the following CWE weaknesses when scanning the project. The root is always `applicationinsights-web-2.0.1.jar`.

High:
- Use of Hard-coded Cryptographic Key (CWE ID 321) (`NTLMEngineImpl.java`)
- Use of a Broken or Risky Cryptographic Algorithm (CWE ID 327) (`NTLMEngineImpl`, ...)

Medium:
- Improper Output Neutralization for Logs (CWE ID 117) (`Jdk14Logger`, ...)
- Insufficient Entropy (CWE ID 331) (`ArrayUtils`, ...)
- Deserialization of Untrusted Data (CWE ID 502) (`BasicAuthCache`)

Low:
- Improper Validation of Certificate with Host Mismatch (CWE ID 297) (`SSLConnectionSocketFactory`)
- Information Exposure Through Sent Data (CWE ID 201) (`AbstractSessionOutputBuffer`, ...)

I'm not seeing those weaknesses in scans before the upgrade, however I'm not 100% sure that the previous package actually contained the `applicationinsights-web` `jar`.

Are CWE weaknesses something the project cares about?

**Comment by dhaval24** [comment]
@tobiasb we had this issue earlier also reported via internal support. Here is the verbatim:

For the high risk components:

NTLMEngineImpl.java (part of apache HTTP client library) – uses DES crypto algo.
MessageDigestCalculatingInputStream.java ( part of apache commons-lang3 library) – uses MD5.

we embed (aka shadow) these libraries into the Application Insights SDK, however, these particular classes are not used within the SDK.
 
I took a look at the latest stable http client (4.5.5, we are on 4.5.3) and it still has the same issue, so even if we upgrade the version, still the issue will persist.
 
Regarding the MEDIUM impact issues, they all revolve around the use of random number generators. Most of them are in the commons-lang3 library. There two in our code. All of these are not an issue because these numbers are not used for security purposes. These generic random number generators is a problem only when they are used for security purposes (such as generating a session identifier or cryptographic key).

So while we are aware of this issues you highlighted none of them apply as such because of the above mentioned reasons. Let me know if there are any other concerns. 

As of previous version we had broken shadow jar which might cause dependency hell issues as these libraries are extremely popular.

**Comment by grlima** [comment]
Known issues with external libraries due to the fact we embed them in the SDK.

**Comment by tobiasb** [comment]
Thank you @dhaval24.

**Comment by anton-chertov** [comment]
@dhaval24 
what about other medium impact issues:
1. Improper Output Neutralization for Logs (CWE ID 117) (Jdk14Logger.java, Jdk13LumberjackLogger.java)
2. Deserialization of Untrusted Data (CWE ID 502) (BasicAuthCache.java)
