### ISSUE TITLE
Documentation: How to run agent in Spring Boot apps

### ISSUE THREAD

**Issue by nikmd23** [microsoft/ApplicationInsights-Java#731]
Our [agent documentation](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-agent) doesn’t show how to run SpringBoot apps via command line along with agent.

@dhaval24, would you mind quickly providing those instructions here, and then we'll update the doc.

**Comment by dhaval24** [comment]
Sure. Here is how you run javaagent with jar file based deployment in springboot.

`java -javaagent:/path/to/agent.jar -jar path/to/TestApp.jar`

Please note that if the the location of AI-Agent.xml and agent jar file should reside in the same folder. They can be placed together in the /resources folder of the project.

@nikmd23  hope this helps.

**Comment by MattyNixon** [comment]
@nikmd23 @dhaval24 

Hi guys, just fixed up our SpringBoot (Docker) application with App Insights and the Agent. Here is some notes from the troubleshooting with @dhaval24 
1) If you have an ApplicationInsights.xml still sitting around, the agent may fail to start if the iKey is not in the XML file (e.g. is injected via a YAML)
2) We added this to our Alpine DockerFile:
ADD AI-Agent.xml /myApp/AI-Agent.xml
ENV JAVA_OPTS="-javaagent:/myApp/applicationinsights-agent-2.2.0.jar"
3) We now inject the iKey at Docker container startup (-e "APPLICATION_INSIGHTS_IKEY=aaaaaa-bbbbb-cccc-dddd-eeeee")

This satisfies the requirements laid out in the original Agent guide about "adding the jar to Tomcat/Linux". On a Windows Server I suspect you'd adjust the environment variables accordingly

That's it!

@dhaval24 what we are really chasing is baked in support for the Agent and SpringBoot so we can use Maven/Gradle to pull the agent dependency through automatically. Can a ticket be raised on this please? We are going to install the Agent jar on our local Maven Repository, but of course we would rather get a definitive version from Maven Central. Also my solution works neatly for Docker but in a plain SpringBoot application it won't be as simple and may not be suitable for a PaaS solution since you no longer have control over the platform

Thanks
-Matt

**Comment by dhaval24** [comment]
@MattyNixon thank you very much for this detailed notes. By the way, would it be possible for you to share a strip down version of your docker springboot setup with Agent? It would help me and other people in community. If you upload, please make sure to remove all sensitive information like Instrumentation Key etc.
