### ISSUE TITLE
Distributed tracing support with Spring Cloud Sleuth

### ISSUE THREAD

**Issue by sabareeshkkanan** [microsoft/ApplicationInsights-Java#793]
We are looking for a APM solution as we are already azure wondering whether we can make use of Application Insight but based on my research I cannot find where it supports Spring Cloud Sleuth which enables distributed tracing.

**Comment by dhaval24** [comment]
@sabareeshkkanan thank you very much for asking your question and apologies for the delay in the response. This is an interesting ask, I would like to better understand your scenario. Application Insights can give you all the diagnostics information and also has innate capability of distributed tracing. We currently use [W3C](https://w3c.github.io/trace-context/) distributed tracing protocol for service to service interaction and capturing the dependencies to form application map and the gant chart for transaction overview. 

Some documentation on how Azure Monitor's experience looks like : https://docs.microsoft.com/en-us/azure/azure-monitor/app/app-map

https://docs.microsoft.com/en-us/azure/application-insights/app-insights-tutorial-performance

However, it is true that currently we do not have integration with Spring cloud sleuth but we plan to add support for it in future and it's in our roadmap. 

As of today, you can still get the full APM experience with Azure Monitor and Application Insights, on Azure UX with minimal work to do on your end.  Please let me know your specific needs and I might be able to help you more.

Cc. @nikmd23 @reyang @lmolkova @xscript

**Comment by florianrusch** [comment]
This issue seems to be a little but unfocused. I was also looking for this integration or something like that.

Our scenario:
We are building a microservice plattform with a lot of Spring Boot backend services and a Angular frontend service. On our local dev deployment we are using Spring Cloud Sleuth in combination with Zipkin/Jaeger for tracing the requests between the services (direct http calls and messaging via Kafka & RabbitMQ).

On our staging/production deployment on azure we would like to use the azure solutions (e.g. application insights). But sadly it seems, that the libs (e.g. applicationinsights-spring-boot-starter) doesn't support Kafka & RabbitMQ. I think the simplest solution for the developers would be an integration with spring cloud sleuth to keep the dependency differences between local and azure deployments as small as possible (for example like the zipkin integration for spring boot.

**Comment by trask** [comment]
> But sadly it seems, that the libs (e.g. applicationinsights-spring-boot-starter) doesn't support Kafka & RabbitMQ

Kafka is supported now in [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent), and we are tracking future RabbitMQ support in #1236.
