### ISSUE TITLE
Support Spark Web Framework

### ISSUE THREAD

**Issue by ifle** [microsoft/ApplicationInsights-Java#867]
I have a project that use the spark web framework
https://github.com/perwendel/spark.
How to integrate the ApplicationInsights to spark?

**Comment by littleaj** [comment]
@ifle, I know of one other user using our SDK in a Spark Application. So, I know it can be done. I'll follow up here when I have more information on how to enable it.

**Comment by dhaval24** [comment]
@ifle I think that you should be able to use Applicationinsights core sdk api's to manually collect telemetry. Our web sdk currently supports servlet stack and we have springboot integration with applicationinsights springboot starter. 
There is no immediate plan to have automatic instrumentation for spark framework, however we encourage and accept contributions. So feel free to raise a PR and we can help review the code :)

**Comment by littleaj** [comment]
@ifle My previous comment was about Apache Spark, which is something different and unrelated. My apologies.

Regarding the Spark Web Framework, since it's Servlet-based you should be able to add the SDK's request filter, `WebRequestTrackingFilter`. I wasn't able to find an explicit example of this, but you may find this issue helpful: https://github.com/perwendel/spark/issues/1089

`applicationinsights-agent.jar` should work as expected. Let us know if you have any more questions about this.

**Comment by trask** [comment]
Spark Web uses Jetty native handlers, which are supported in Application Insights Java 3.x
