### ISSUE TITLE
Seeing NullPointerException on latest 2.4.1-Beta version

### ISSUE THREAD

**Issue by prabhushrikant** [Microsoft/ApplicationInsights-Java#895]
### Expected behavior
- Controller tests should pass but instead started receiving Nullpointer exception.

### Actual behavior
java.lang.NullPointerException at com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.doFilter

### To Reproduce
- Write a simple controller test 
- Try to execute the same

```@RunWith(SpringJUnit4ClassRunner.class)
@WebMvcTest(value = SimpleController.class, secure = false)
@ContextConfiguration(classes = {ControllerTestInitializer.class})
@Slf4j
public class SimpleControllerTests {

  @Autowired
  private MockMvc mockMvc;

@Test
  public void testGetVersionSuccess() throws Exception { 
    <...test logic >
}
```

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version:  Java 1.8u202
 - OS type and version: Ubuntu Linux 1604
 - Application Server type and version (if applicable): Tomcat 9.0.16
 - Using spring-boot? Yes , Spring boot 2.1.3
 - Additional relevant libraries (with version, if applicable): Guice 

### Logs
java.lang.NullPointerException at com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.doFilter

**Comment by prabhushrikant** [comment]
I will tonight.

**Comment by dhaval24** [comment]
@prabhushrikant this is expected. The Spring MVC Test suite is not meant to test the filter chain as well. It doesn't call the `init()` method of the WebFilters and therefore the `WebRequestTrackingFilter` throws NPE. 
You can do either of the following to fix this behavior:
1. Add a setup method in your current code which relies on MockMvc for tests.

```
@Before
	public void setup() {
		WebRequestTrackingFilter filter = new WebRequestTrackingFilter();
		filter.init(new MockFilterConfig()); // using a mock that you construct with init params and all
		this.mockMvc = webAppContextSetup(this.webAppContext)
				.addFilters(filter).build();
	}
```
Or instead of relying on MockMvc use the something like this:

```
RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
public class HttpRequestTest {

    @LocalServerPort
    private int port;

    @Autowired
    private TestRestTemplate restTemplate;

    @Test
    public void greetingShouldReturnDefaultMessage() throws Exception {
        assertThat(this.restTemplate.getForObject("http://localhost:" + port + "/",
                String.class)).contains("Hello World");
    }
}
```
which instantiates the test server.

Please refer to https://spring.io/guides/gs/testing-web/ and https://stackoverflow.com/questions/20819130/whats-required-to-make-mockmvc-test-a-filters-init-routine for more details.

I will close this for now. Please reopen if issue still persists.
