### ISSUE TITLE
Security vulnerabilities in applicationinsights-web & applicationinsightsspring-boot-starter

### ISSUE THREAD

**Issue by Ravuthaumar** [microsoft/ApplicationInsights-Java#986]
We are using AppInsight for log aggregation in spring boot services hosted on Azure. When we ran veracode security scan, it reported following flaws in applicationInsight and ApplicatiionInsight spring-boot-starter. Wanted to check if you are aware of the issues and have plan to fix them in the upcoming releases.

1) applicationinsights-web-2.4.0.jar
   - Use of a Broken or Risky Cryptographic Algorithm (CWE ID 327) in MessageDigestCalculatingInputStream.java (88)
   - Information Exposure Through Sent Data (CWE ID 201)(5 flaws) in ByteArrayOutputStream.java 262, ChunkedOutputStream.java 81, ProxyOutputStream.java 89, TeeOutputStream.java 64, ThresholdingOutputStream.java 128
   
2) applicationinsightsspring-boot-starter-1.1.1.jar
   - Improper Resource Shutdown or Release (CWE ID 404)(1 flaw) in com/.../language/bm/Languages.java (154)

**Comment by Ravuthaumar** [comment]
Hello team,

Can you please update us when these issues will be resolved?

Thanks

**Comment by littleaj** [comment]
* MessageDigestCalculatingInputStream: CWE ID 327 does not apply here because this is not an encryption related class. Also, we don't use it.
* CWE ID 201: We do use ByteArrayOutputStream to transmit data, but it is encrypted before it's sent.
* CWE ID 404: this looks like a false positive. The Scanner used in Languages.java appears to be closed properly
